version: "3.8"

services:
    app:
        build: .
        volumes:
            - .:/code_pcentra
        ports:
            - "8000:8000"
        image: django_pcentra:django
        container_name: django_pcentra_container
        command: >
            sh -c "python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DOCKER_ENV=True
